CREATE TABLE IF NOT EXISTS zoo(zoo_id varchar(100) primary key not null,zoo_name varchar(100) NOT NULL, zoo_location varchar(100) NOT NULL, zoo_hours INT NOT NULL, zoo_contact bigint NOT NULL);
INSERT INTO zoo(zoo_id, zoo_name, zoo_location, zoo_hours, zoo_contact) VALUES (%s,%s,%s,%s,%s), (zoo_id, zoo_name, zoo_location, zoo_hours, zoo_contact));
SELECT * FROM ZOO;
UPDATE ZOO SET zoo_name=%s, zoo_location=%s, zoo_hours=%s, zoo_contact=%s WHERE zoo_id=%s ", (new_zoo_name, new_zoo_location, new_zoo_hours, new_zoo_contact, zoo_id));
DELETE FROM ZOO WHERE zoo_id=%s, (zoo_id,);
CREATE TABLE IF NOT EXISTS CUSTOMER(cust_id varchar(100) PRIMARY KEY NOT NULL,cust_fname varchar(100) NOT NULL,cust_lname varchar(100) NOT NULL, cust_email varchar(100) NOT NULL, cust_address varchar(100) NOT NULL, cust_cred_no bigint NOT NULL);
INSERT INTO CUSTOMER(cust_id, cust_fname, cust_lname, cust_email, cust_address, cust_cred_no) VALUES (%s,%s,%s,%s,%s,%s);
SELECT * FROM CUSTOMER;
UPDATE CUSTOMER SET cust_fname=%s, cust_lname=%s, cust_email=%s, cust_address=%s, cust_cred_no=%s WHERE cust_id=%s , (new_cust_fname, new_cust_lname, new_cust_email, new_cust_address, new_cust_cred_no, cust_id));
DELETE FROM CUSTOMER WHERE cust_id=%s, (cust_id,);
CREATE TABLE IF NOT EXISTS TICKET(ticket_id varchar(100) not null,order_date date,price float,age int,primary key(ticket_id));
INSERT INTO TICKET(ticket_id, order_date, price, age) VALUES (%s,%s,%s,%s), (ticket_id, order_date, price, age);
SELECT * FROM TICKET;
UPDATE TICKET SET order_date=%s, price=%s , age=%s WHERE ticket_id=%s, (new_order_date, new_price, new_age, ticket_id);
DELETE FROM TICKET WHERE ticket_id=%s, (ticket_id,);
CREATE TABLE IF NOT EXISTS EMPLOYEE(emp_id varchar(100) not null,emp_name varchar(100),emp_des varchar(100),phone_num bigint,salary float,primary key(emp_id));
INSERT INTO EMPLOYEE(emp_id, emp_name, emp_des, phone_num, salary) VALUES (%s,%s,%s,%s,%s), (emp_id, emp_name, emp_des, phone_num, salary));
SELECT * FROM EMPLOYEE;
UPDATE EMPLOYEE SET emp_name=%s, emp_des=%s, phone_num=%s, salary=%s WHERE emp_id=%s, (new_emp_name, new_emp_des, new_phone_num, new_salary, emp_id);
DELETE FROM EMPLOYEE WHERE emp_id=%s, (emp_id,);
CREATE TABLE IF NOT EXISTS ANIMAL(animal_id varchar(100) not null,animal_name varchar(100),cage_num varchar(100),gender varchar(100),height varchar(100),weight varchar(100),age varchar(100),diet varchar(100),status varchar(100),primary key(animal_id));
INSERT INTO ANIMAL(animal_id, animal_name, cage_num, gender, height, weight,age,diet,status) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s)', (animal_id, animal_name, cage_num, gender, height, weight,age,diet,status);
SELECT * FROM ANIMAL;
UPDATE ANIMAL SET animal_name=%s, cage_num=%s, gender=%s, height=%s, weight=%s, age=%s, diet=%s, status=%s  WHERE emp_id=%s", (new_animal_name, new_cage_num, new_gender, new_height, new_weight, new_age, new_diet, new_status, animal_id);
DELETE FROM ANIMAL WHERE animal_id=%s, (animal_id,);
SELECT animal_count();
call updtdemployee();
select tkt_discount();
call modify_ticket();
